# Generated by Django 5.2.8 on 2025-11-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Необязательное поле. Введите телеграм id",
                max_length=100,
                null=True,
                verbose_name="телеграмм id",
            ),
        ),
    ]
