# Generated by Django 5.2.8 on 2025-11-23 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time_to_action",
            field=models.TimeField(
                default=datetime.timedelta(seconds=120),
                verbose_name="Время на выполнение",
            ),
        ),
    ]
