# Generated by Django 5.2.8 on 2025-11-24 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_alter_habits_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="time_to_action",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                verbose_name="Время на выполнение",
            ),
        ),
    ]
